name: Discord Bot CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Change to your Node.js version

      - name: Install dependencies
        run: npm install discord.js

      - name: Run Discord Bot
        run: echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: node index.js  # Replace with your bot's main file
